version: 2
jobs:
  build:
    docker:
      - image: haskell:8.0.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cabal update && cabal install test-framework test-framework-quickcheck2
      - run:
          name: Build
          command: ghc Math.hs Math_tests.hs -o Tests
      - run:
          name: Tests
          command: ./Tests
